"""
Django settings for ecualizer_config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@t%c*x6bv(u2c2$o4e8$6=wxz074)tfs&w1be#x8@6%eu-w0(d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

# Nota: la autenticación de Ecualizer es propia y se apoya en MongoDB Atlas
# (ver usuarios/mongo_service.py) + sesiones en cookies firmadas. NO se usa
# django.contrib.auth para iniciar sesión ni el admin integrado de Django
# (ambos requieren una BD relacional, que aquí no existe). Se conserva
# django.contrib.auth solo porque expone los hashers de contraseñas
# (make_password / check_password) que reutiliza mongo_service.
INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarios',
    'catalogo',
    'biblioteca',
    'pagos',
    'analitica',
    'industria',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    # AuthenticationMiddleware removido: resolvía request.user contra la BD
    # relacional (dummy) y rompía las páginas cuando el navegador enviaba una
    # cookie de sesión antigua con _auth_user_id. La app usa request.session.
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                # 'django.contrib.auth.context_processors.auth' removido:
                # inyectaba request.user (resuelto contra la BD relacional).
                'django.contrib.messages.context_processors.messages',
                'usuarios.context_processors.notificaciones_oyente',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.dummy',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Sesiones en cookies firmadas — no requiere tabla django_session en BD.
# El login_Administrador no tiene permiso CREATE TABLE en SQL Server.
# Límite ~4KB por sesión (suficiente para usuario_id, tipo, nombre).
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'


# ──────────────────────────────────────────────────────────
# LOGGING — debug de registro/auth
# Salida en consola + archivo `ecualizer.log` en la raíz del proyecto.
# ──────────────────────────────────────────────────────────
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'detallado': {
            'format': '[{asctime}] {levelname:7s} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'detallado',
            'level': 'DEBUG',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'ecualizer.log',
            'formatter': 'detallado',
            'level': 'DEBUG',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'ecualizer.registro': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'ecualizer.auth': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'ecualizer.biblioteca': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'ecualizer.analitica': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# Spotify API
SPOTIFY_CLIENT_ID = '7a24e29fb30b4cf5a46861df271d7784'
SPOTIFY_CLIENT_SECRET = '28c0a8ed5c6242538c2c273da17b6f6f'

# ─────────────────────────────────────────────
# Caché en archivo — persiste entre reinicios del servidor.
# Las secciones del oyente (Para Ti, Tendencias, Novedades, Explorar)
# no vuelven a llamar a Spotify hasta que expire el TTL, incluso
# si el servidor se reinicia.
# ─────────────────────────────────────────────
import os as _os
_CACHE_DIR = _os.path.join(BASE_DIR, '.django_cache')
_os.makedirs(_CACHE_DIR, exist_ok=True)

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': _CACHE_DIR,
        'TIMEOUT': 60 * 60 * 6,        # 6 horas — Spotify no cambia tan rápido
        'OPTIONS': {'MAX_ENTRIES': 300},
    }
}

# Segundos que se cachean los resultados de las secciones del oyente.
SPOTIFY_CACHE_TTL = 60 * 60 * 6  # 6 horas